options:
  tmp_dir: /var/tmp
shared:
  domain: uds.local
variables:
  minio-operator:
    ADDITIONAL_NETWORK_ALLOW:
      - direction: Ingress
        remoteNamespace: mattermost
        remoteSelector:
          kubernetes.io/name: mattermost
        port: 9000
    TENANT_POOLS: 
      - servers: 1
        name: mattermost
        volumesPerServer: 1
        size: 50Gi